# Generated by Django 4.2.7 on 2023-12-03 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoanNews',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('writer', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'boannews',
                'managed': False,
            },
        ),
    ]
